name: village_rentals_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  flutter_easyloading: ^3.0.5
  to_csv: ^2.2.1
  intl:
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

